"""Create users table

Revision ID: 48cfd011f54b
Revises: 135d22cc63dc
Create Date: 2026-07-15 16:43:27.381269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cfd011f54b'
down_revision: Union[str, Sequence[str], None] = '135d22cc63dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('photo', sa.String(length=150), nullable=True))
    op.execute(
        "UPDATE products "
        "SET photo = 'images/products/no-photo.jpg' "
        "WHERE photo IS NULL"
    )
    op.alter_column('products', 'photo', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'photo')
    # ### end Alembic commands ###
